% **************************************
% Set Base Params
% **************************************
readPath = 'E:\Thesis Results\External Beam Trials (Redo).xls';
sheet = 'OSC-TV_ All Trials';

groupLabels = {...
    '\begin{tabular}{c}4 Gy\end{tabular}',...
    '\begin{tabular}{c}12 Gy\end{tabular}',...
    '\begin{tabular}{c}16 Gy\end{tabular}',...
    '\begin{tabular}{c}20 Gy\end{tabular}'};

groupRows = {...
    3:5,...
    6:8,...
    9:11,...
    12:14};    

subgroupLabels = {...
    'Control',...
    'FDK',...
    'OSC-TV'};

subgroupColours = [...
    0.75 0.75 0.75;...
    0.25 0.25 0.25;...
    0.5 0.5 0.5];

customColours = {...
    [],...
    [],...
    [],...
    []};

figDimsInCm = [5, 7.4];

subgroupLabelWriteIndex = 1;

% **************************************
% Mean
% **************************************

graphWritePath = 'E:\Thesis Figures\Results\OSC-TV\Dose Level Bar Graphs\Mean Comparison.png';

column = 28;

yAxisLabel = '$\bar{\Delta\mu}_{ROI}$ $[cm^-1]$';

title = '$\bar{\Delta\mu}_{ROI}$';

f = @(x) x ./ 100;

subgroupLabelOrientation = {...
    'above',...
    'above',...
    'above'};

subgroupLabelAngle = {...
    60,...
    60,...
    60};

lineAtBar = [];
linePosAndNeg = true;

barGraphDataCollectionAndCreation(...
    readPath, sheet, groupRows, column,...
    graphWritePath, groupLabels, subgroupLabels,...
    subgroupLabelWriteIndex, subgroupLabelOrientation, subgroupLabelAngle,...
    figDimsInCm, subgroupColours, customColours,...
    yAxisLabel, title, f, lineAtBar, linePosAndNeg); 


% **************************************
% Stdev
% **************************************

graphWritePath = 'E:\Thesis Figures\Results\OSC-TV\Dose Level Bar Graphs\Stdev Comparison.png';

column = 31;

yAxisLabel = '$\sigma_{ROI}$ $[cm^-1]$';

title = '$\sigma_{ROI}$';

f = @(x) x ./ 100;

subgroupLabelOrientation = {...
    'above',...
    'above'};

subgroupLabelAngle = {...
    50,...
    50};

lineAtBar = [];
linePosAndNeg = true;

subgroupLabels = {...
    };

subgroupLabelWriteIndex = Inf;

barGraphDataCollectionAndCreation(...
    readPath, sheet, groupRows, column,...
    graphWritePath, groupLabels, subgroupLabels,...
    subgroupLabelWriteIndex, subgroupLabelOrientation, subgroupLabelAngle,...
    figDimsInCm, subgroupColours, customColours,...
    yAxisLabel, title, f, lineAtBar, linePosAndNeg); 

% **************************************
% Gradient Mean
% **************************************

graphWritePath = 'E:\Thesis Figures\Results\OSC-TV\Dose Level Bar Graphs\Gradient Comparison.png';

column = 34;

yAxisLabel = '$\bar{\nabla}_{ROI}$ $[cm^{-1} / mm]$';

title = '$\bar{\nabla}_{ROI}$';

f = @(x) x ./ 100;

subgroupLabelOrientation = {...
    'above',...
    'above'};

subgroupLabelAngle = {...
    50,...
    50};

lineAtBar = [];
linePosAndNeg = true;

barGraphDataCollectionAndCreation(...
    readPath, sheet, groupRows, column,...
    graphWritePath, groupLabels, subgroupLabels,...
    subgroupLabelWriteIndex, subgroupLabelOrientation, subgroupLabelAngle,...
    figDimsInCm, subgroupColours, customColours,...
    yAxisLabel, title, f, lineAtBar, linePosAndNeg); 

% **************************************
% Delta Mean
% **************************************

groupRows = {...
    4:5,...
    7:8,...
    10:11,...
    13:14};   

subgroupLabels = {...
    };

subgroupColours = [...
    0.25 0.25 0.25;...
    0.5, 0.5, 0.5];


graphWritePath = 'E:\Thesis Figures\Results\OSC-TV\Dose Level Bar Graphs\Delta Comparison.png';

column = 40;

yAxisLabel = '$\bar{\Delta}_{ROI}$ $[cm^{-1}]$';

title = '$\bar{\Delta}_{ROI}$';

f = @(x) x ./ 100;

subgroupLabelOrientation = {...
    'above',...
    'above'};

subgroupLabelAngle = {...
    50,...
    50};

lineAtBar = [];
linePosAndNeg = true;

barGraphDataCollectionAndCreation(...
    readPath, sheet, groupRows, column,...
    graphWritePath, groupLabels, subgroupLabels,...
    subgroupLabelWriteIndex, subgroupLabelOrientation, subgroupLabelAngle,...
    figDimsInCm, subgroupColours, customColours,...
    yAxisLabel, title, f, lineAtBar, linePosAndNeg); 

