usedFloodFields = false;

gel3Cath_osctv = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-3)\', 1, usedFloodFields);

gel3and5Cath_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-1\Gel 5-1_HR.vff');
gel3Cath_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-3\Gel 5-3_HR.vff');


gel5Cath_osctv = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-4)\', 1, usedFloodFields);

gel5Cath_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-4\Gel 5-4_HR.vff');

% analysis params
slice = 128;

threshold2000MU = [0, 13.4];

ticks2000MU = [];%[0:3:12, 13.4];

colourbarLabel = '$\Delta\mu$ $[cm^{-1}]$';


imageHeightInCm = 2.5;

unitConversion = 1/100; % m-1 to cm-1


profile1_X = [44 216];
profile1_Y = [67 186];

profile2_X = [59 228];
profile2_Y = [47 164];

% profile1_X = [1 256];
% profile1_Y = [128 128];
% 
% profile2_X = [128 128];
% profile2_Y = [1 256];


lineColours = {...
    [1 0 0],...
    [0 0 1],...
    [0 0 0]};

lineStyles = {...
    '-',...
    '-',...
    '--'};

lineWidths = {1, 1, 1};

legendLabels = {...
    'FDK',...
    'OSC-TV',...    
    'Control'};

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7.5,7.5];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\Delta\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\OSC-TV\Profiles\';

writeSliceImagesFromFigure(...
    [root, '3 Catheters.png'],...
    gel3Cath_osctv(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {profile1_X, profile2_X}, {profile1_Y, profile2_Y}, {[1 0 0],[1 0 0]}, {'-','-'}, {2,2});

yLims = [-0.025, 0.2];

takeAndPlotLineProfiles(...
    [root, '3 Catheters Profiles 1.png'],...
    {gel3Cath_fdk, gel3Cath_osctv, gel3and5Cath_control},...
    {noShift, noShift, [0 0]},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

% yLims = [];
% 
% takeAndPlotLineProfiles(...
%     [root, '3 Catheters Profiles 2.png'],...
%     {gel3Cath_fdk, gel3Cath_osctv, gel3and5Cath_control},...
%     {noShift, noShift, [0 0]},...
%     unitConversion, slice,...
%     profile2_X, profile2_Y, voxelDimInMM,...
%     lineProfilePlotDimsInCm, yLims,...
%     lineProfileXAxis, lineProfileYAxis,...
%     lineStyles, lineColours, lineWidths, legendLabels);


writeSliceImagesFromFigure(...
    [root, '5 Catheters.png'],...
    gel5Cath_osctv(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {profile1_X, profile2_X}, {profile1_Y, profile2_Y}, {[1 0 0],[1 0 0]}, {'-','-'}, {2,2});

yLims = [-0.005, 0.155];

takeAndPlotLineProfiles(...
    [root, '5 Catheters Profiles 1.png'],...
    {gel5Cath_fdk, gel5Cath_osctv, gel3and5Cath_control},...
    {noShift, noShift, [0 1]},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

% yLims = [];
% 
% takeAndPlotLineProfiles(...
%     [root, '5 Catheters Profiles 2.png'],...
%     {gel5Cath_fdk, gel5Cath_osctv, gel3and5Cath_control},...
%     {noShift, noShift, [0 1]},...
%     unitConversion, slice,...
%     profile2_X, profile2_Y, voxelDimInMM,...
%     lineProfilePlotDimsInCm, yLims,...
%     lineProfileXAxis, lineProfileYAxis,...
%     lineStyles, lineColours, lineWidths, legendLabels);


