usedFloodFields = false;


gel2000MU_osctv = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2)\', 57, usedFloodFields);
gel2000MU_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-1\Gel 4-1_HR.vff');
gel2000MU_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-2\Gel 4-2_HR.vff');

% analysis params
botSlice = 128+64;
midSlice = 128;
topSlice = 128-64;


threshold2000MU = [0, 13.4];

ticks2000MU = [];%[0:3:12, 13.4];

colourbarLabel = '$\Delta\mu$ $[cm^{-1}]$';


imageHeightInCm = 2.2;

unitConversion = 1/100; % m-1 to cm-1

lineColours = {...
    };

lineStyles = {...
   };

lineWidths = {};

legendLabels = {...
    };

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\Delta\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\OSC-TV\Consistency Axial Slices\';

writeSliceImagesFromFigure(...
    [root, 'Bot 1500MU OSC-TV.png'],...
    gel2000MU_osctv(:,:,botSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Mid 2000MU OSC-TV.png'],...
    gel2000MU_osctv(:,:,midSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Top 2000MU OSC-TV.png'],...
    gel2000MU_osctv(:,:,topSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Bot 2000MU FDK.png'],...
    gel2000MU_fdk(:,:,botSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Mid 2000MU FDK.png'],...
    gel2000MU_fdk(:,:,midSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Top 2000MU FDK.png'],...
    gel2000MU_fdk(:,:,topSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Bot 2000MU Control.png'],...
    gel2000MU_control(:,:,botSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Mid 2000MU Control.png'],...
    gel2000MU_control(:,:,midSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Top 2000MU Control.png'],...
    gel2000MU_control(:,:,topSlice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

