% Load up OSC-TV_FF
usedFloodFields = true;

gel500MU_osctv_FF = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-2 FF-R)\', 1, usedFloodFields);
gel1500MU_osctv_FF = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-4 FF-R)\', 51, usedFloodFields);
gel2000MU_osctv_FF = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2 FF-R)\', 57, usedFloodFields);
gel2500MU_osctv_FF = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-4 FF-R)\', 1, usedFloodFields);

% Load up OSC-TV_RR
usedFloodFields = false;

gel500MU_osctv_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-2)\', 2, usedFloodFields);
gel1500MU_osctv_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-4)\', 52, usedFloodFields);
gel2000MU_osctv_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2)\', 157, usedFloodFields);
gel2500MU_osctv_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-4)\', 2, usedFloodFields);

% Load up OSC-TV_FF_RR
usedFloodFields = true;

gel500MU_osctv_FF_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-2 FF-R)\', 2, usedFloodFields);
gel1500MU_osctv_FF_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-4 FF-R)\', 52, usedFloodFields);
gel2000MU_osctv_FF_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2 FF-R)\', 157, usedFloodFields);
gel2500MU_osctv_FF_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-4 FF-R)\', 2, usedFloodFields);


% analysis params
slice = 128;

threshold500MU = [0, 2.9];
threshold1500MU = [0, 9.7];
threshold2000MU = [0, 13.4];
threshold2500MU = [0, 16.5];

ticks500MU = [];%[0:0.5:2.5, 2.9];
ticks1500MU = [];%[0:2:8, 9.7];
ticks2000MU = [];%[0:3:12, 13.4];
ticks2500MU = [];%[0:4:16, 16.5];

colourbarLabel = '$\Delta\mu$ $[cm^{-1}]$';


imageHeightInCm = 2.2;

unitConversion = 1/100; % m-1 to cm-1

lineColours = {...
    };

lineStyles = {...
   };

lineWidths = {};

legendLabels = {...
    };

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\Delta\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\OSC-TV Variants\Dose Level Axial Slices\';

% OSC-TV_FF
writeSliceImagesFromFigure(...
    [root, '500MU Catheter FF.png'],...
    gel500MU_osctv_FF(:,:,slice),...
    unitConversion, threshold500MU,...
    imageHeightInCm, ticks500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1500MU Catheter FF.png'],...
    gel1500MU_osctv_FF(:,:,slice),...
    unitConversion, threshold1500MU,...
    imageHeightInCm, ticks1500MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '2000MU Catheter FF.png'],...
    gel2000MU_osctv_FF(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '2500MU Catheter FF.png'],...
    gel2500MU_osctv_FF(:,:,slice),...
    unitConversion, threshold2500MU,...
    imageHeightInCm, ticks2500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

% OSC-TV_RR

writeSliceImagesFromFigure(...
    [root, '500MU Catheter RR.png'],...
    gel500MU_osctv_RR(:,:,slice),...
    unitConversion, threshold500MU,...
    imageHeightInCm, ticks500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1500MU Catheter RR.png'],...
    gel1500MU_osctv_RR(:,:,slice),...
    unitConversion, threshold1500MU,...
    imageHeightInCm, ticks1500MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '2000MU Catheter RR.png'],...
    gel2000MU_osctv_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '2500MU Catheter RR.png'],...
    gel2500MU_osctv_RR(:,:,slice),...
    unitConversion, threshold2500MU,...
    imageHeightInCm, ticks2500MU, colourbarLabel,...
    {}, {}, {}, {}, {});


% OSC-TV_FF_RR

writeSliceImagesFromFigure(...
    [root, '500MU Catheter FF RR.png'],...
    gel500MU_osctv_FF_RR(:,:,slice),...
    unitConversion, threshold500MU,...
    imageHeightInCm, ticks500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1500MU Catheter FF RR.png'],...
    gel1500MU_osctv_FF_RR(:,:,slice),...
    unitConversion, threshold1500MU,...
    imageHeightInCm, ticks1500MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '2000MU Catheter FF RR.png'],...
    gel2000MU_osctv_FF_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '2500MU Catheter FF RR.png'],...
    gel2500MU_osctv_FF_RR(:,:,slice),...
    unitConversion, threshold2500MU,...
    imageHeightInCm, ticks2500MU, colourbarLabel,...
    {}, {}, {}, {}, {});
