% Load up OSC-TV_FF
usedFloodFields = true;

gel1Cath_osctv_FF = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2 FF-R)\', 57, usedFloodFields);
gel1CathOffset_osctv_FF = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-2 FF-R)\', 1, usedFloodFields);
gel3Cath_osctv_FF = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-3 FF-R)\', 1, usedFloodFields);
gel5Cath_osctv_FF = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-4 FF-R)\', 1, usedFloodFields);

% Load up OSC-TV_RR
usedFloodFields = false;

gel1Cath_osctv_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2)\', 157, usedFloodFields);
gel1CathOffset_osctv_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-2)\', 2, usedFloodFields);
gel3Cath_osctv_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-3)\', 2, usedFloodFields);
gel5Cath_osctv_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-4)\', 2, usedFloodFields);

% Load up OSC-TV_FF_RR
usedFloodFields = true;

gel1Cath_osctv_FF_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2 FF-R)\', 157, usedFloodFields);
gel1CathOffset_osctv_FF_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-2 FF-R)\', 2, usedFloodFields);
gel3Cath_osctv_FF_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-3 FF-R)\', 2, usedFloodFields);
gel5Cath_osctv_FF_RR = loadGyrfalconReconForFigures('E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 5-4 FF-R)\', 2, usedFloodFields);


% analysis params
slice = 128;

threshold2000MU = [0, 13.4];

ticks2000MU = [];%[0:3:12, 13.4];

colourbarLabel = '$\Delta\mu$ $[cm^{-1}]$';


imageHeightInCm = 2.2;

unitConversion = 1/100; % m-1 to cm-1

lineColours = {...
    };

lineStyles = {...
   };

lineWidths = {};

legendLabels = {...
    };

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\Delta\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\OSC-TV Variants\Num Catheters Axial Slices\';

% OSC-TV_FF
writeSliceImagesFromFigure(...
    [root, '1 Catheter FF.png'],...
    gel1Cath_osctv_FF(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1 Catheter Offset FF.png'],...
    gel1CathOffset_osctv_FF(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '3 Catheter FF.png'],...
    gel3Cath_osctv_FF(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '5 Catheter FF.png'],...
    gel5Cath_osctv_FF(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

% OSC-TV_RR

writeSliceImagesFromFigure(...
    [root, '1 Catheter RR.png'],...
    gel1Cath_osctv_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1 Catheter Offset RR.png'],...
    gel1CathOffset_osctv_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '3 Catheter RR.png'],...
    gel3Cath_osctv_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '5 Catheter RR.png'],...
    gel5Cath_osctv_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


% OSC-TV_FF_RR

writeSliceImagesFromFigure(...
    [root, '1 Catheter FF RR.png'],...
    gel1Cath_osctv_FF_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1 Catheter Offset FF RR.png'],...
    gel1CathOffset_osctv_FF_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '3 Catheter FF RR.png'],...
    gel3Cath_osctv_FF_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});


writeSliceImagesFromFigure(...
    [root, '5 Catheter FF RR.png'],...
    gel5Cath_osctv_FF_RR(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});
