function [] = writeLineProfiles_Gel7_2b()
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here

readPath = 'E:\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2b\Slicer Exports\';

cali = [0.046828 186.995401];

loadData = load([readPath, 'TPS.mat']);
tps = loadData.volume;

loadData = load([readPath, 'FDK.mat']);
fdk = applyCalibration(loadData.volume, cali);

loadData = load([readPath, 'OSC-TV.mat']);
osctv = applyCalibration(loadData.volume, cali);

loadData = load([readPath, 'OSC-TV_RR.mat']);
osctv_RR = applyCalibration(loadData.volume, cali);

profile1_X = [27 232];
profile1_Y = [128 128];

profile2_X = [27 232];
profile2_Y = [128+30 128+30];

lineColours = {...
    [1 0 0],...
    [0 0 1],...
    [0 0.75 0],...
    [0 0 0]};

lineStyles = {...
    '-',...
    '-',...
    '-',...
    '--'};

lineWidths = {1, 1, 1, 1};

legendLabels = {...
    'FDK',...
    'OSC-TV',...   
    'OSC-TV_R_R',...  
    'Control'};

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7.5,7.5];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = 'Absolute Dose $[Gy]$';

noShift = [0 0];

axialSlice = 128;
axialThreshold = [0, 40];
axialTicks = [];
axialSliceSizeInCm = 2;

colourbarLabel = 'Absolute Dose $[Gy]$';
unitConversion = 1;

% write axial slices

root = 'E:\Thesis Figures\Results\HDR\OncoSmart (1 Cath, 5 Dwell)\Line Profiles\';

writeSliceImagesFromFigure(...
    [root, 'TPS Profile Display.png'],...
    tps(:,:,axialSlice),...
    unitConversion, axialThreshold,...    
    axialSliceSizeInCm, axialTicks, colourbarLabel,...
    {profile1_X, profile2_X}, {profile1_Y, profile2_Y}, {[1 0 0],[1 0 0]}, {'-','-'}, {2,2});

yLims = [-10,500];

takeAndPlotLineProfiles(...
    [root, 'Profiles 1.png'],...
    {fdk, osctv, osctv_RR, tps},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, axialSlice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

yLims = [-5, 30];

takeAndPlotLineProfiles(...
    [root, 'Profiles 2.png'],...
    {fdk, osctv, osctv_RR, tps},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, axialSlice,...
    profile2_X, profile2_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

end

