function [] = writeDoseSlices_Gel7_2b()
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here

readPath = 'E:\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2b\Slicer Exports\';

cali = [0.046828 186.995401];

loadData = load([readPath, 'TPS.mat']);
tps = loadData.volume;

loadData = load([readPath, 'FDK.mat']);
fdk = applyCalibration(loadData.volume, cali);

loadData = load([readPath, 'OSC-TV.mat']);
osctv = applyCalibration(loadData.volume, cali);

loadData = load([readPath, 'OSC-TV_RR.mat']);
osctv_RR = applyCalibration(loadData.volume, cali);

axialSlice = 128;
axialThreshold = [0, 40];
axialTicks = [];
axialSliceSizeInCm = 5;

transSlice = 128;
transThreshold = [0, 40];
transTicks = [];
transSliceSizeInCm = 5;

colourbarLabel = 'Absolute Dose $[Gy]$';
unitConversion = 1;

% write axial slices

root = 'E:\Thesis Figures\Results\HDR\OncoSmart (1 Cath, 5 Dwell)\Slices\';

writeSliceImagesFromFigure(...
    [root, 'TPS Axial.png'],...
    tps(:,:,axialSlice),...
    unitConversion, axialThreshold,...
    axialSliceSizeInCm, axialTicks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'FDK Axial.png'],...
    fdk(:,:,axialSlice),...
    unitConversion, axialThreshold,...
    axialSliceSizeInCm, axialTicks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'OSC-TV Axial.png'],...
    osctv(:,:,axialSlice),...
    unitConversion, axialThreshold,...
    axialSliceSizeInCm, axialTicks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'OSC-TV_RR Axial.png'],...
    osctv_RR(:,:,axialSlice),...
    unitConversion, axialThreshold,...
    axialSliceSizeInCm, axialTicks, colourbarLabel,...
    {}, {}, {}, {}, {});

% write transverse slices

root = 'E:\Thesis Figures\Results\HDR\OncoSmart (1 Cath, 5 Dwell)\\Slices\';

writeSliceImagesFromFigure(...
    [root, 'TPS Trans.png'],...
    getTransverseSlice(tps, transSlice),...
    unitConversion, transThreshold,...
    transSliceSizeInCm, transTicks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'FDK Trans.png'],...
    getTransverseSlice(fdk, transSlice),...
    unitConversion, transThreshold,...
    transSliceSizeInCm, transTicks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'OSC-TV Trans.png'],...
    getTransverseSlice(osctv, transSlice),...
    unitConversion, transThreshold,...
    transSliceSizeInCm, transTicks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'OSC-TV_RR Trans.png'],...
    getTransverseSlice(osctv_RR, transSlice),...
    unitConversion, transThreshold,...
    transSliceSizeInCm, transTicks, colourbarLabel,...
    {}, {}, {}, {}, {});

end

