
gel500MU_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-1\Gel 2-1_HR.vff');
gel500MU_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-2\Gel 2-2_HR.vff');

gel1500MU_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-3\Gel 2-3_HR.vff');
gel1500MU_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-4\Gel 2-4_HR.vff');

gel2000MU_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-1\Gel 4-1_HR.vff');
gel2000MU_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-2\Gel 4-2_HR.vff');

gel2500MU_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-3\Gel 4-3_HR.vff');
gel2500MU_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-4\Gel 4-4_HR.vff');

% analysis params
slice = 128;

threshold500MU = [0, 2.9];
threshold1500MU = [0, 9.7];
threshold2000MU = [0, 13.4];
threshold2500MU = [0, 16.5];

ticks500MU = [];%[0:0.5:2.5, 2.9];
ticks1500MU = [];%[0:2:8, 9.7];
ticks2000MU = [];%[0:3:12, 13.4];
ticks2500MU = [];%[0:4:16, 16.5];

colourbarLabel = '$\Delta\mu$ $[cm^{-1}]$';


imageHeightInCm = 2.2;

unitConversion = 1/100; % m-1 to cm-1

lineColours = {...
    };

lineStyles = {...
   };

lineWidths = {};

legendLabels = {...
    };

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\Delta\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\Artifact Characterization\Dose Level Axial Slices\';

writeSliceImagesFromFigure(...
    [root, '500MU Control.png'],...
    gel500MU_control(:,:,slice),...
    unitConversion, threshold500MU,...
    imageHeightInCm, ticks500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '500MU Catheter.png'],...
    gel500MU_fdk(:,:,slice),...
    unitConversion, threshold500MU,...
    imageHeightInCm, ticks500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1500MU Control.png'],...
    gel1500MU_control(:,:,slice),...
    unitConversion, threshold1500MU,...
    imageHeightInCm, ticks1500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1500MU Catheter.png'],...
    gel1500MU_fdk(:,:,slice),...
    unitConversion, threshold1500MU,...
    imageHeightInCm, ticks1500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '2000MU Control.png'],...
    gel2000MU_control(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '2000MU Catheter.png'],...
    gel2000MU_fdk(:,:,slice),...
    unitConversion, threshold2000MU,...
    imageHeightInCm, ticks2000MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '2500MU Control.png'],...
    gel2500MU_control(:,:,slice),...
    unitConversion, threshold2500MU,...
    imageHeightInCm, ticks2500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '2500MU Catheter.png'],...
    gel2500MU_fdk(:,:,slice),...
    unitConversion, threshold2500MU,...
    imageHeightInCm, ticks2500MU, colourbarLabel,...
    {}, {}, {}, {}, {});

