
gel1Cath_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-1\Gel 4-1_HR.vff');
gel1Cath_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-2\Gel 4-2_HR.vff');

gel1CathOffset_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-1\Gel 5-1_HR.vff');
gel1CathOffset_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-2\Gel 5-2_HR.vff');

gel3Cath_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-1\Gel 5-1_HR.vff');
gel3Cath_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-3\Gel 5-3_HR.vff');

gel5Cath_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-1\Gel 5-1_HR.vff');
gel5Cath_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 5-4\Gel 5-4_HR.vff');

% analysis params
slice = 128;


threshold = [0, 13.4];

ticks = [];

colourbarLabel = '$\Delta\mu$ $[cm^{-1}]$';


imageHeightInCm = 2.2;

unitConversion = 1/100; % m-1 to cm-1

lineColours = {...
    };

lineStyles = {...
   };

lineWidths = {};

legendLabels = {...
    };

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\Delta\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\Artifact Characterization\Num Catheters Axial Slices\';

writeSliceImagesFromFigure(...
    [root, '1 Cath Control.png'],...
    gel1Cath_control(:,:,slice),...
    unitConversion, threshold,...
    imageHeightInCm, ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1 Cath Catheter.png'],...
    gel1Cath_fdk(:,:,slice),...
    unitConversion, threshold,...
    imageHeightInCm, ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1 Cath Offset Control.png'],...
    gel1CathOffset_control(:,:,slice),...
    unitConversion, threshold,...
    imageHeightInCm, ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '1 Cath Offset Catheter.png'],...
    gel1CathOffset_fdk(:,:,slice),...
    unitConversion, threshold,...
    imageHeightInCm, ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '3 Cath Control.png'],...
    gel3Cath_control(:,:,slice),...
    unitConversion, threshold,...
    imageHeightInCm, ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '3 Cath Catheter.png'],...
    gel3Cath_fdk(:,:,slice),...
    unitConversion, threshold,...
    imageHeightInCm, ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '5 Cath Control.png'],...
    gel5Cath_control(:,:,slice),...
    unitConversion, threshold,...
    imageHeightInCm, ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, '5 Cath Catheter.png'],...
    gel5Cath_fdk(:,:,slice),...
    unitConversion, threshold,...
    imageHeightInCm, ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

