function detectorData = runBeamTraceHighPerformanceWrapper(scan, source, detector, slicePosition, angle, zStep, xyStep, zDetector, xyDetector, phantomData, phantomDims, voxelDimsInM, phantomLocationInM, beamCharacterization, scatteringNoiseLevel, detectorNoiseLevel, partialPixel, partialPixelResolution)
% detectorData = runBeamTraceHighPerformanceWrapper()

phantomData = phantomData.Value;
beamCharacterization = beamCharacterization.Value;
% 
% scan = scan.Value;
% source = source.Value;
% detector = detector.Value;

displayDetectorRayTrace = false;
axesHandle = []; % unneeded

[perAngleXY, perAngleZ] = scan.getPerAnglePositionInM(xyStep, zStep);

diameter = [];

[...
    sourceStartBoxCoords,...
    sourceEndBoxCoords,...
    sourceDirectionUnitVector,...
    ~] = ...
    source.getSourcePosition(...
    slicePosition,...
    angle,...
    perAngleXY,...
    perAngleZ,...
    diameter);

[xCoords, yCoords, zCoords] = getAllDetectorCoords(detector, slicePosition, angle, perAngleXY, perAngleZ);

clockwisePosZ = [xCoords(zDetector,xyDetector), yCoords(zDetector,xyDetector), zCoords(zDetector,xyDetector)];
clockwiseNegZ = [xCoords(zDetector+1,xyDetector), yCoords(zDetector+1,xyDetector), zCoords(zDetector+1,xyDetector)];
counterClockwisePosZ = [xCoords(zDetector,xyDetector+1), yCoords(zDetector,xyDetector+1), zCoords(zDetector,xyDetector+1)];
counterClockwiseNegZ = [xCoords(zDetector+1,xyDetector+1), yCoords(zDetector+1,xyDetector+1), zCoords(zDetector+1,xyDetector+1)];

detectorCornerCoords = [clockwisePosZ; clockwiseNegZ; counterClockwisePosZ; counterClockwiseNegZ];

[detectorData,~,~] = runBeamTrace(...
    axesHandle,...
    sourceStartBoxCoords,...
    sourceEndBoxCoords,...
    sourceDirectionUnitVector,...
    detectorCornerCoords,...
    phantomData,...
    phantomDims,...
    voxelDimsInM,...
    phantomLocationInM,...
    beamCharacterization,...
    scatteringNoiseLevel,...
    detectorNoiseLevel,...
    partialPixel,...
    partialPixelResolution,...
    displayDetectorRayTrace);


end

