% load-up images
preFdk_2_4 = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-4 (FF-R)\Gel 2-4 (FF-R)_HR.vff');
postFdk_2_4 = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-4 (FF-D)\Gel 2-4 (FF-D)_HR.vff');

preFdk_2_4_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-3 (FF-R)\Gel 2-3 (FF-R)_HR.vff');
postFdk_2_4_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-3 (FF-D)\Gel 2-3 (FF-D)_HR.vff');

preFdk_4_2 = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-2 (FF-R)\Gel 4-2 (FF-R)_HR.vff');
postFdk_4_2 = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-2 (FF-D)\Gel 4-2 (FF-D)_HR.vff');

preFdk_4_2_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-1 (FF-R)\Gel 4-1 (FF-R)_HR.vff');
postFdk_4_2_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-1 (FF-D)\Gel 4-1 (FF-D)_HR.vff');


% analysis params
slice = 128;

gel2_4_threshold = [0, 17];
gel4_2_threshold = [0, 26];

gel2_4_ticks = [0:2:16,17];
gel4_2_ticks = [0:3:24, 26];

colourbarLabel = '$\mu$ $[cm^{-1}]$';

imageThreshold = [0 2^16];

profile1_X = [1 256];
profile1_Y = [128 128];

profile2_X = [1 256];
profile2_Y = [110 110];

imageHeightInCm = 6;

unitConversion = 1/100; % m-1 to cm-1

lineColours = {...
    [1 0 0],...
    [0 0 1],...
    [1 0 0],...
    [0 0 1]};

lineStyles = {...
    ':',...
    ':',...
    '-',...
    '-'};

lineWidths = {1, 1, 1, 1};

legendLabels = {...
    'Control (Pre)',...
    'Control (Post)',...
    'Catheter (Pre)',...
    'Catheter (Post)'};

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\FDK_FF\';

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Control Pre.png'],...
    preFdk_2_4_control(:,:,slice),...
    unitConversion, gel2_4_threshold,...
    imageHeightInCm, gel2_4_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Control Post.png'],...
    postFdk_2_4_control(:,:,slice),...
    unitConversion, gel2_4_threshold,...
    imageHeightInCm, gel2_4_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Cath Pre.png'],...
    preFdk_2_4(:,:,slice),...
    unitConversion, gel2_4_threshold,...
    imageHeightInCm, gel2_4_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Cath Post.png'],...
    postFdk_2_4(:,:,slice),...
    unitConversion, gel2_4_threshold,...
    imageHeightInCm, gel2_4_ticks, colourbarLabel,...
    {profile1_X, profile2_X}, {profile1_Y, profile2_Y}, {[1 0 0],[1 0 0]}, {'-','-'}, {2,2});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Control Pre.png'],...
    preFdk_4_2_control(:,:,slice),...
    unitConversion, gel4_2_threshold,...
    imageHeightInCm, gel4_2_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Control Post.png'],...
    postFdk_4_2_control(:,:,slice),...
    unitConversion, gel4_2_threshold,...
    imageHeightInCm, gel4_2_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Cath Pre.png'],...
    preFdk_4_2(:,:,slice),...
    unitConversion, gel4_2_threshold,...
    imageHeightInCm, gel4_2_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Cath Post.png'],...
    postFdk_4_2(:,:,slice),...
    unitConversion, gel4_2_threshold,...
    imageHeightInCm, gel4_2_ticks, colourbarLabel,...
    {profile1_X, profile2_X}, {profile1_Y, profile2_Y}, {[1 0 0],[1 0 0]}, {'-','-'}, {2,2});

%% Write profiles

yLims = [-0.03, 0.8];

takeAndPlotLineProfiles(...
    [root, 'Gel 2-4 Profiles 1.png'],...
    {preFdk_2_4_control, postFdk_2_4_control, preFdk_2_4, postFdk_2_4},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

yLims = [-0.03, 0.8];

takeAndPlotLineProfiles(...
    [root, 'Gel 2-4 Profiles 2.png'],...
    {preFdk_2_4_control, postFdk_2_4_control, preFdk_2_4, postFdk_2_4},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, slice,...
    profile2_X, profile2_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

yLims = [-0.03, 0.8];

takeAndPlotLineProfiles(...
    [root, 'Gel 4-2 Profiles 1.png'],...
    {preFdk_4_2_control, postFdk_4_2_control, preFdk_4_2, postFdk_4_2},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

yLims = [-0.03, 0.8];

takeAndPlotLineProfiles(...
    [root, 'Gel 4-2 Profiles 2.png'],...
    {preFdk_4_2_control, postFdk_4_2_control, preFdk_4_2, postFdk_4_2},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, slice,...
    profile2_X, profile2_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);


%% ************************************
%% Write projection data files


data = load('E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-4)\Slice 1\Angle 0\Position (1,1) Detector Data.mat');

pre2_4_fdk = data.detectorData_I0(35:35+700-1, 163:163+700-1);
post2_4_fdk = data.detectorData_I(35:35+700-1, 163:163+700-1);

data = load('E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2)\Slice 1\Angle 0\Position (1,1) Detector Data.mat');

pre4_2_fdk = data.detectorData_I0(35:35+700-1, 163:163+700-1);
post4_2_fdk = data.detectorData_I(35:35+700-1, 163:163+700-1);

% analysis params
slice = 1;

rawDataThreshold = [0, 2^16];
lnDataThreshold = []; %auto

rawDataTicks = [0, 2^15, 2^16];
lnDataTicks = [];

rawDataColourbarLabel = 'Detector Value $[unitless]$';
lnDataColourbarLabel = '$ln(I_0/I) $ $[unitless]$';

profile1_X = [293 392];
profile1_Y = [350 350];

imageHeightInCm = 6;

unitConversion = 1; % non-needed

lineColours = {...
    [1 0 0],...
    [0 0 1]};

lineStyles = {...
    '-',...
    '-'};

lineWidths = {1, 1};

legendLabels = {...
    'Pre',...
    'Post'};

lnLegendLabels = {...
    '1500MU',...
    '2000MU'};

voxelDimInMM = 1;

noShift = [0 0];

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Pixel Position $[unitless]$';
lineProfileYAxis = 'Detector Value $[unitless]$';

%% Images

root = 'G:\Thesis Figures\Artifact Cause and Effect\Pre and Post\';

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Pre.png'],...
    pre2_4_fdk,...
    unitConversion, rawDataThreshold,...
    imageHeightInCm, rawDataTicks, rawDataColourbarLabel,...
    {profile1_X}, {profile1_Y}, {[1 0 0]}, {'-'}, {2});

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Post.png'],...
    post2_4_fdk,...
    unitConversion, rawDataThreshold,...
    imageHeightInCm, rawDataTicks, rawDataColourbarLabel,...
    {profile1_X}, {profile1_Y}, {[1 0 0]}, {'-'}, {2});

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Ln.png'],...
    log(pre2_4_fdk./post2_4_fdk),...
    unitConversion, lnDataThreshold,...
    imageHeightInCm, lnDataTicks, lnDataColourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Pre.png'],...
    pre4_2_fdk,...
    unitConversion, rawDataThreshold,...
    imageHeightInCm, rawDataTicks, rawDataColourbarLabel,...
    {profile1_X}, {profile1_Y}, {[1 0 0]}, {'-'}, {2});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Post.png'],...
    post4_2_fdk,...
    unitConversion, rawDataThreshold,...
    imageHeightInCm, rawDataTicks, rawDataColourbarLabel,...
    {profile1_X}, {profile1_Y}, {[1 0 0]}, {'-'}, {2});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Ln.png'],...
    log(pre4_2_fdk./post4_2_fdk),...
    unitConversion, lnDataThreshold,...
    imageHeightInCm, lnDataTicks, lnDataColourbarLabel,...
    {profile1_X}, {profile1_Y}, {[1 0 0]}, {'-'}, {2});

%% Write profiles

yLims = [0, 2^16 / 2];

takeAndPlotLineProfiles(...
    [root, 'Gel 2-4 Profiles 1.png'],...
    {pre2_4_fdk, post2_4_fdk},...
    {noShift, noShift},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

yLims = [0, 2^16 / 2];

takeAndPlotLineProfiles(...
    [root, 'Gel 4-2 Profiles 1.png'],...
    {pre4_2_fdk, post4_2_fdk},...
    {noShift, noShift},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

yLims = [0.2, 1.2];
lineProfileYAxis = '$ln(I_0/I) $ $[unitless]$';

lineColours = {...
    [0 0 0],...
    [0 0 0]};

lineStyles = {...
    '-',...
    ':'};

takeAndPlotLineProfiles(...
    [root, 'Gel 4-2 vs 2-4 Ln Profiles 1.png'],...
    {log(pre2_4_fdk./post2_4_fdk), log(pre4_2_fdk./post4_2_fdk)},...
    {[6,0], noShift},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, lnLegendLabels);

%% Difference figures and plots

fdk_2_4 = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-4\Gel 2-4_HR.vff');
fdkFF_2_4 = postFdk_2_4 - preFdk_2_4;

diff_2_4 = fdkFF_2_4 - fdk_2_4;

fdk_4_2 = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-2\Gel 4-2_HR.vff');
fdkFF_4_2 = postFdk_4_2 - preFdk_4_2;

diff_4_2 = fdkFF_4_2 - fdk_4_2;

root = 'E:\Thesis Figures\Results\FDK_FF\';

colourbarLabel = '$\Delta\mu$ (FDK$_{FF}$ - FDK) $[cm^{-1}]$';

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Diff.png'],...
    diff_2_4(:,:,slice),...
    unitConversion, [],...
    imageHeightInCm, [], colourbarLabel,...
    {profile1_X}, {profile1_Y}, {[1 0 0]}, {'-'}, {2});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Diff.png'],...
    diff_4_2(:,:,slice),...
    unitConversion, [],...
    imageHeightInCm, [], colourbarLabel,...
    {profile1_X}, {profile1_Y}, {[1 0 0]}, {'-'}, {2});

yLims = [];

lineProfileYAxis = '$\Delta\mu$ (FDK$_{FF}$ - FDK) $[cm^{-1}]$';

lineColours = {...
    [1 0 0],...
    [0 0 0]};

lineStyles = {...
    '-',...
    ':'};

legendLabels = {...
    '1500MU',...
    '2000MU'};

takeAndPlotLineProfiles(...
    [root, 'FDK_FF vs FDK Line Profiles 1.png'],...
    {diff_2_4, diff_4_2},...
    {[6,0], noShift},...
    1, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths,legendLabels);
