%% ****************************
% Gel 4-2 Slices and Profiles

gel4_2_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-1\Gel 4-1_HR.vff');
gel4_2_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 4-2\Gel 4-2_HR.vff');

reconNum = 54;
usedFloodFields = false;

gel4_2_osctv = loadGyrfalconReconForFigures(...
    'E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2)\',...
    reconNum, usedFloodFields);

reconNum = 54;
usedFloodFields = true;

gel4_2_osctv_ff = loadGyrfalconReconForFigures(...
    'E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 4-2 FF-R)\',...
    reconNum, usedFloodFields);

% analysis params
slice = 128;

gel4_2_threshold = [0, 13];

gel4_2_ticks = [0:2:12, 13];

colourbarLabel = '$\Delta\mu$ $[cm^{-1}]$';

profile1_X = [1 256];
profile1_Y = [128 128];

profile2_X = [1 256];
profile2_Y = [110 110];

imageHeightInCm = 6;

unitConversion = 1/100; % m-1 to cm-1

lineColours = {...
    [0 0 0],...
    [1 0 0],...
    [0 0.5 0],...
    [0 0 1]};

lineStyles = {...
    ':',...
    '-',...
    '-',...
    '-'};

lineWidths = {1, 1, 1, 1};

legendLabels = {...
    'Control',...
    'FDK',...
    'OSC-TV',...
    'OSC-TV_{FF}'};

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\Delta\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\OSC-TV_FF All Trials\';

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 Control.png'],...
    gel4_2_control(:,:,slice),...
    unitConversion, gel4_2_threshold,...
    imageHeightInCm, gel4_2_ticks, colourbarLabel,...
    {profile1_X, profile2_X}, {profile1_Y, profile2_Y}, {[1 0 0],[1 0 0]}, {'-','-'}, {2,2});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 FDK.png'],...
    gel4_2_fdk(:,:,slice),...
    unitConversion, gel4_2_threshold,...
    imageHeightInCm, gel4_2_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 OSC-TV.png'],...
    gel4_2_osctv(:,:,slice),...
    unitConversion, gel4_2_threshold,...
    imageHeightInCm, gel4_2_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 4-2 OSC-TV FF.png'],...
    gel4_2_osctv_ff(:,:,slice),...
    unitConversion, gel4_2_threshold,...
    imageHeightInCm, gel4_2_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});


%% Write profiles

yLims = [-0.02 0.3];

takeAndPlotLineProfiles(...
    [root, 'Gel 4-2 Profiles 1.png'],...
    {gel4_2_control, gel4_2_fdk, gel4_2_osctv, gel4_2_osctv_ff},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

yLims = [-0.02 0.19];

takeAndPlotLineProfiles(...
    [root, 'Gel 4-2 Profiles 2.png'],...
    {gel4_2_control, gel4_2_fdk, gel4_2_osctv, gel4_2_osctv_ff},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, slice,...
    profile2_X, profile2_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);


%% ****************************
% Gel 2-4 Slices and Profiles

gel2_4_control = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-3\Gel 2-3_HR.vff');
gel2_4_fdk = loadOpticalCtVistaRecon('E:\Thesis Recon Data\Gel 2-4\Gel 2-4_HR.vff');

reconNum = 1;
usedFloodFields = false;

gel2_4_osctv = loadGyrfalconReconForFigures(...
    'E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-4)\',...
    reconNum, usedFloodFields);

reconNum = 1;
usedFloodFields = true;

gel2_4_osctv_ff = loadGyrfalconReconForFigures(...
    'E:\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 2-4 FF-R)\',...
    reconNum, usedFloodFields);

% analysis params
slice = 128;

gel2_4_threshold = [0, 9];

gel2_4_ticks = [0:2:8, 9];

colourbarLabel = '$\Delta\mu$ $[cm^{-1}]$';

profile1_X = [1 256];
profile1_Y = [128 128];

profile2_X = [1 256];
profile2_Y = [110 110];

imageHeightInCm = 6;

unitConversion = 1/100; % m-1 to cm-1

lineColours = {...
    [0 0 0],...
    [1 0 0],...
    [0 0.5 0],...
    [0 0 1]};

lineStyles = {...
    ':',...
    '-',...
    '-',...
    '-'};

lineWidths = {1, 1, 1, 1};

legendLabels = {...
    'Control',...
    'FDK',...
    'OSC-TV',...
    'OSC-TV_{FF}'};

voxelDimInMM = 0.5;

lineProfilePlotDimsInCm = [7,7];
lineProfileXAxis = 'Position $[mm]$';
lineProfileYAxis = '$\Delta\mu$ $[cm^{-1}]$';

noShift = [0 0];


%% Write images

root = 'E:\Thesis Figures\Results\OSC-TV_FF All Trials\';

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 Control.png'],...
    gel2_4_control(:,:,slice),...
    unitConversion, gel2_4_threshold,...
    imageHeightInCm, gel2_4_ticks, colourbarLabel,...
    {profile1_X, profile2_X}, {profile1_Y, profile2_Y}, {[1 0 0],[1 0 0]}, {'-','-'}, {2,2});

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 FDK.png'],...
    gel2_4_fdk(:,:,slice),...
    unitConversion, gel2_4_threshold,...
    imageHeightInCm, gel2_4_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 OSC-TV.png'],...
    gel2_4_osctv(:,:,slice),...
    unitConversion, gel2_4_threshold,...
    imageHeightInCm, gel2_4_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});

writeSliceImagesFromFigure(...
    [root, 'Gel 2-4 OSC-TV FF.png'],...
    gel2_4_osctv_ff(:,:,slice),...
    unitConversion, gel2_4_threshold,...
    imageHeightInCm, gel2_4_ticks, colourbarLabel,...
    {}, {}, {}, {}, {});


%% Write profiles

yLims = [-0.02 0.3];

takeAndPlotLineProfiles(...
    [root, 'Gel 2-4 Profiles 1.png'],...
    {gel2_4_control, gel2_4_fdk, gel2_4_osctv, gel2_4_osctv_ff},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, slice,...
    profile1_X, profile1_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);

yLims = [-0.02 0.19];

takeAndPlotLineProfiles(...
    [root, 'Gel 2-4 Profiles 2.png'],...
    {gel2_4_control, gel2_4_fdk, gel2_4_osctv, gel2_4_osctv_ff},...
    {noShift, noShift, noShift, noShift},...
    unitConversion, slice,...
    profile2_X, profile2_Y, voxelDimInMM,...
    lineProfilePlotDimsInCm, yLims,...
    lineProfileXAxis, lineProfileYAxis,...
    lineStyles, lineColours, lineWidths, legendLabels);