function [] = convertGyrfalconReconstrutionsToVff()
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here

readInfo = {...
    'F:\Thesis Recon Data\Gel 6-2a\Gel 6-2a_HR.vff', 0, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 6-2a)\', 1, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 6-2a)\', 2, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 6-2a FF-R)\' 1, true, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 6-2a FF-R)\' 2, true, [0 1 1];...
    ...
    'F:\Thesis Recon Data\Gel 6-3b\Gel 6-3b_HR.vff', 0, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 6-3b)\', 1, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 6-3b)\', 2, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 6-3b FF-R)\' 1, true, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 6-3b FF-R)\' 2, true, [0 1 1];...
    ...
    'F:\Thesis Recon Data\Gel 7-2a\Gel 7-2a_HR.vff', 0, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-2a)\', 1, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-2a)\', 2, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-2a FF-R)\' 1, true, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-2a FF-R)\' 2, true, [0 1 1];...
    ...
    'F:\Thesis Recon Data\Gel 7-2b\Gel 7-2b_HR.vff', 0, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-2b)\', 1, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-2b)\', 2, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-2b FF-R)\' 1, true, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-2b FF-R)\' 2, true, [0 1 1];...
    ...
    'F:\Thesis Recon Data\Gel 7-3\Gel 7-3_HR.vff', 0, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-3)\', 1, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-3)\', 2, false, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-3 FF-R)\' 1, true, [0 1 1];...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\Imaging Scan Runs\Optical CT Imaging Scan Run (Gel 7-3 FF-R)\' 2, true, [0 1 1]...
};

writePaths = {...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-2a\Gel 6-2a FDK.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-2a\Gel 6-2a OSC-TV.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-2a\Gel 6-2a OSC-TV_RR.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-2a\Gel 6-2a OSC-TV_FF.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-2a\Gel 6-2a OSC-TV_FF_RR.vff',...
    ...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-3b\Gel 6-3b FDK.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-3b\Gel 6-3b OSC-TV.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-3b\Gel 6-3b OSC-TV_RR.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-3b\Gel 6-3b OSC-TV_FF.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 6-3b\Gel 6-3b OSC-TV_FF_RR.vff',...
    ...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2a\Gel 7-2a FDK.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2a\Gel 7-2a OSC-TV.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2a\Gel 7-2a OSC-TV_RR.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2a\Gel 7-2a OSC-TV_FF.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2a\Gel 7-2a OSC-TV_FF_RR.vff',...
    ...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2b\Gel 7-2b FDK.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2b\Gel 7-2b OSC-TV.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2b\Gel 7-2b OSC-TV_RR.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2b\Gel 7-2b OSC-TV_FF.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-2b\Gel 7-2b OSC-TV_FF_RR.vff',...
    ...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-3\Gel 7-3 FDK.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-3\Gel 7-3 OSC-TV.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-3\Gel 7-3 OSC-TV_RR.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-3\Gel 7-3 OSC-TV_FF.vff',...
    'E:\Data Files\Git Repos\Local Gyrfalcon Data\HDR Irradiations\Gel 7-3\Gel 7-3 OSC-TV_FF_RR.vff'...    
};

   

for i=1:length(writePaths)
    disp(i);
    
    if readInfo{i,2} == 0 % FDK Load
        volume = loadOpticalCtVistaRecon(readInfo{i,1});
    else
        volume = loadGyrfalconReconForFigures(readInfo{i,1}, readInfo{i,2}, readInfo{i,3});
    end
    
    writeReconstructionToVff(volume, writePaths{i}, readInfo{i,4});
end

end

